# Generated by Django 3.1.6 on 2021-02-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_a', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='expenditure',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='income',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='savings',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
