# Generated by Django 3.0.1 on 2021-02-06 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget_a', '0003_auto_20210206_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incomemodel',
            old_name='date_of_exp',
            new_name='date_of_inc',
        ),
    ]
